before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y rabbitmq-server"
  - "sudo /usr/sbin/rabbitmq-server -detached"

before_script:
  "rake vendor && rake codegen:ffi"
script:
  "rake"
after_script:
  "rake install"

language: ruby
rvm:
  - 2.1
  - 2.2
  - rbx-2

notifications:
  email: false
