before_install:
  - "if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y rabbitmq-server; fi"
  - "if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install rabbitmq && sudo /usr/local/sbin/rabbitmq-server &; fi"

before_script:
  "rake vendor && rake codegen:ffi"
script:
  "rake spec"
after_script:
  "rake install"

language: ruby
rvm:
  - 2.1
os:
  - linux
  - osx

notifications:
  email: false
